# Change these first
owner: rustama1211 # Your GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  - name: Berocca
    url: https://berocca.co.id
  - name: Benpanthen
    url: https://bepanthen.co.id
  - name: Zambuk
    url: https://zambuk.co.id
  - name: CDR
    url: https://cdr.co.id
  - name: Saridon
    url: https://saridon.co.id
  - name: Canesten
    url: https://canesten.co.id
  - name: Tonikum
    url: https://tonikum.co.id
  - name: Redoxon
    url: https://redoxon.co.id
  - name: Clarityn
    url: https://clarityn.co.id

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: statuses.otesuto.com
  #baseUrl: /up
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Status
  navbar:
    - title: Status
      href: /
 #   - title: GitHub
 #     href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
